### ISSUE TITLE
Error when trying to get 'light_curve' from QuadLightCurve

### ISSUE THREAD

**Issue by catrionamurray** [exoplanet-dev/exo4jax#2]
I created a basic fake transit through exo4jax (still familiarizing so let me know if I've made any silly mistakes!):

`mstar = 0.98`
`rstar = 0.93`
`time_transit = 0.0`
`period = 1`
`b = 0.5`
`rr = 0.1`
`ld = [0.1,0.3]`
`t = np.linspace(-0.1,0.1,1000)`

`host_star = orbits.KeplerianCentral.init(mass=mstar,radius=rstar)`

`planet = orbits.KeplerianBody.init(
        central=host_star,
        time_transit=time_transit,
        period=period,
        impact_param=b,
        radius=jnp.array(rr * rstar))`
    
`orbit = orbits.KeplerianOrbit(planet)`
`lc = light_curves.QuadLightCurve(ld[0], ld[1])`
`lc_to_return = lc.light_curve(planet, t)`

But I run into this error at the final stage:
`---------------------------------------------------------------------------
IndexError                                Traceback (most recent call last)
File ~/opt/anaconda3/envs/jax_chromatic/lib/python3.9/site-packages/jax/_src/api.py:1603, in _mapped_axis_size.<locals>._get_axis_size(name, shape, axis)
   1602 try:
-> 1603   return shape[axis]
   1604 except (IndexError, TypeError) as e:

IndexError: tuple index out of range

The above exception was the direct cause of the following exception:

ValueError                                Traceback (most recent call last)
Input In [742], in <cell line: 21>()
     19 orbit = orbits.KeplerianOrbit(planet)
     20 lc = light_curves.QuadLightCurve(ld[0], ld[1])
---> 21 lc_to_return = lc.light_curve(planet, t)

File ~/opt/anaconda3/envs/jax_chromatic/lib/python3.9/site-packages/exo4jax/_src/light_curves.py:88, in QuadLightCurve.light_curve(***failed resolving arguments***)
     86 r = orbit.radius / r_star
     87 lc_func = partial(light_curve, self.u1, self.u2, order=order)
---> 88 lc = jax.vmap(lc_func)(b, r)
     89 return jnp.where(z > 0, lc, 0)

    [... skipping hidden 6 frame]

File ~/opt/anaconda3/envs/jax_chromatic/lib/python3.9/site-packages/jax/_src/api.py:1606, in _mapped_axis_size.<locals>._get_axis_size(name, shape, axis)
   1604 except (IndexError, TypeError) as e:
   1605   min_rank = axis + 1 if axis >= 0 else -axis
-> 1606   raise ValueError(
   1607       f"{name} was requested to map its argument along axis {axis}, "
   1608       f"which implies that its rank should be at least {min_rank}, "
   1609       f"but is only {len(shape)} (its shape is {shape})") from e

ValueError: vmap was requested to map its argument along axis 0, which implies that its rank should be at least 1, but is only 0 (its shape is ())`

**Comment by catrionamurray** [comment]
I tried hacking the code where the error is happening a little, I think it might be an issue with the shape of `r`. If I replace the `.light_curve` step with:

`r_star = planet.central_radius
x, y, z = planet.relative_position(t)
b = jnp.sqrt(x**2 + y**2) / r_star
r = planet.radius / r_star
lc_func = partial(light_curve, lc.u1, lc.u2, order=10)
lc = jax.vmap(lc_func)(b, jnp.array([r] * len(b)))`

(which is basically your code with r replaced by  jnp.array([r] * len(b)))
Then it seems to run OK

**Comment by dfm** [comment]
What if you just use:

```
radius=rr * rstar
```

Instead of

```
radius=jnp.array(rr * rstar)
```

Does that work? I'm not at my computer to play around with it right now.

**Comment by catrionamurray** [comment]
> What if you just use:
> 
> ```
> radius=rr * rstar
> ```
> 
> Instead of
> 
> ```
> radius=jnp.array(rr * rstar)
> ```
> 
> Does that work? I'm not at my computer to play around with it right now.

I actually spotted that just before I saw your reply, unfortunately it doesn't seem to change anything
